# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.ssh.insert_key = false

  config.vm.define "web" do |web|
    web.vm.box="jginev/bun2serv"
    web.vm.hostname = "web.do1.lab"
    web.vm.network "private_network", ip: "192.168.89.100"
    web.vm.network "forwarded_port", guest: 80, host: 8080, auto_correct: true
    web.vm.synced_folder "vagrant/web/", "/vagrant"
    web.vm.provision "shell", path: "web.sh"
  end

  config.vm.define "db" do |db|
    db.vm.box="jginev/bun2serv"
    db.vm.hostname = "db.do1.lab"
    db.vm.network "private_network", ip: "192.168.89.101"
    db.vm.synced_folder "vagrant/db/", "/vagrant"
    db.vm.provision "shell", path: "db.sh"
  end

end
